[FIX] #Fixed Typos by codespell
Z4nzu/hackingtool pull request #350
Opened 2023-03-04 14:15 UTC by Z4nzu

Close #347

2023-03-04 14:17 UTC, Z4nzu commented
Hello @cclauss, Please review this branch and approve

2023-03-04 14:22 UTC, cclauss commented
Just add this change https://github.com/Z4nzu/hackingtool/issues/347#issuecomment-1454750557) and then if the tests are green, you are good to go.

2023-03-04 14:25 UTC, cclauss requested changes
Make codespell a mandatory test https://github.com/Z4nzu/hackingtool/issues/347#issuecomment-1454750557

2023-03-04 14:30 UTC, Z4nzu commented
> Make codespell a mandatory test [#347 (comment)](https://github.com/Z4nzu/hackingtool/issues/347#issuecomment-1454750557)
> 
> Don't worry about the failing `push` test. That is fixed on `master`.

I did. Please check

2023-03-04 14:35 UTC, cclauss approved these changes

2023-03-04 14:39 UTC, merged

2023-03-04 14:42 UTC, cclauss commented
9 open issues and 7 open pull requests -- Today was spring cleaning!!

2025-04-20 00:35 UTC, couragexchange approved these changes

2025-04-20 00:35 UTC, couragexchange commented on tools/information_gathering_tools.py
>      DESCRIPTION = "ReconSpider is most Advanced Open Source Intelligence (OSINT)" \
]】