Update README.md
Z4nzu/hackingtool pull request #405
Opened 2023-08-16 17:20 UTC by Aryan01b

Just some Typo corrections.

2023-08-17 08:25 UTC, kulvir758 approved these changes

2023-10-24 07:29 UTC, gaurovgiri requested changes

2023-10-24 07:29 UTC, gaurovgiri commented on README.md
> +### steganography tools
```suggestion
### Steganography tools
```

2023-10-28 08:57 UTC, ISNNOZ approved these changes

2023-10-28 08:57 UTC, ISNNOZ commented on README.md
>  - StegnoCracker
not working for the time being

2024-10-23 19:23 UTC, closed without merging