Added a new link for image of Linux
Z4nzu/hackingtool pull request #421
Opened 2023-10-25 17:43 UTC by Shreyas0410

This resolves #420 
In the current version of README.md file the link for the image of linux is broken. This was fixed in this pr 

![Screenshot 2023-10-25 231240](https://github.com/Z4nzu/hackingtool/assets/70795867/401badd9-2528-4434-a89b-7c90d0abf8ce)

2023-10-25 17:48 UTC, Shreyas0410 commented
@Z4nzu please review.

2023-11-08 12:12 UTC, HouseSteppa approved these changes

2023-11-08 15:09 UTC, temer555 commented
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <base target="_top" />
    <style type="text/css">
      @font-face {
      font-family: "Iceberg";
      font-style: normal;
      font-weight: 400;
      src: url(https://fonts.gstatic.com/s/iceberg/v10/8QIJdijAiM7o-qnZiI8Eqg.woff2)
      format("woff2");
      }
      body {
      background-color: #1b1d27 !important;
      margin: 0 !important;
      font-family: Iceberg, Arial, sans-serif !important;
      text-align: center;
      }
      h2 {
      color: yellowgreen;
      font-size: 20px;
      }
      #maintitle {
      color: red;
      font-size: 38px;
      }
    </style>
  </head>
  <body oncontextmenu="return false;">
    <br><br><br>
    <span id="maintitle">Error</span>
    <h2><?!= passedData ?></h2>
    <br><br>
    2023 © Catz
  </body>
</html>
<!-- / -->

2024-09-26 05:50 UTC, vignesh1507 requested changes
We can optimise the img more.

2024-10-23 19:23 UTC, closed without merging